django_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('product.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProductView.as_view(), name="home"),
    path('shop/', views.ProductListView.as_view(), name="product_list"),
    path('filter/', views.ProductFilterView.as_view(), name="product_filter"),
    path('search/', views.SearchListView.as_view(), name="search"),
    path('add-rating/', views.AddStarRating.as_view(), name="add_rating"),
    # path('json-filter/', views.JsonProductFilterView.as_view(), name="product_filter_json"),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('review/<int:pk>', views.AddReview.as_view(), name="add_review"),
]

product/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Avg

class Category(models.Model):
    name = models.CharField("Категорія", max_length=255)
    slug = models.SlugField("Псевдонім", max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_count_products(self):
        return self.product_set.count()

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Color(models.Model):
    name = models.CharField("Колір", max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Колір"
        verbose_name_plural = "Кольора"

class Size(models.Model):
    name = models.CharField("Розмір", max_length=5)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Розмір"
        verbose_name_plural = "Розміри"


class Action(models.Model):
    name = models.CharField("Назва акції", max_length=20)
    color = models.CharField("Колір", max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Акція"
        verbose_name_plural = "Акції"

class Brand(models.Model):
    name = models.CharField("Бренд", max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Бренд"
        verbose_name_plural = "Бренди"

class Tag(models.Model):
    name = models.CharField("Тег", max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

class Product(models.Model):
    name = models.CharField("Продукт", max_length=255)
    slug = models.SlugField("Псевдонім", max_length=255)
    price = models.PositiveIntegerField("Ціна", default=0)
    product_code = models.CharField("Код продукту", max_length=20)
    shipping_tax = models.PositiveSmallIntegerField("Податок за доставку", default=0)
    description = models.TextField("Опис")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    tag = models.ManyToManyField(Tag, blank=True)
    public = models.BooleanField("Публікація", default=True)
    created_at = models.DateTimeField("Дата створення", auto_now_add=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"slug": self.slug})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_price_discount(self):
        discount = self.productaction_set.filter(product_id=self.id).exclude(value=0).first()
        if discount:
            price = self.price - self.price * discount.value / 100
        else:
            price = self.price
        return price

    def get_general_rating(self):
        return self.rating_set.aggregate(Avg('star'))

    def get_size_names(self):
        list_name = []
        for quantity in self.quantity_set.all():
            list_name.append(quantity.size.name)
        return list_name


    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товари"


class ProductAction(models.Model):
    value = models.PositiveIntegerField("Значення", default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Акція продукта"
        verbose_name_plural = "Акції продуктів"


class Quantity(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField("Кількість", default=0)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, null=True)
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "Кількість"
        verbose_name_plural = "Кількості"


class Image(models.Model):
    name = models.ImageField("Назва", upload_to="img/")
    root = models.BooleanField("Головне фото", default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Фотографія"
        verbose_name_plural = "Фотографії"


class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField("Значення зірок", default=0)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = "Рейтингава зірка"
        verbose_name_plural = "Рейтингові зірки"
        ordering = ["-value"]

class Rating(models.Model):
    ip = models.CharField("IP адреса", max_length=20)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class SocialNetwork(models.Model):
    name = models.CharField("Назва", max_length=40)
    url = models.CharField("URL силка", max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Соціальна мережа"
        verbose_name_plural = "Соціальні мережі"


class Reviews(models.Model):
    """Отзиви"""
    email = models.EmailField("Email")
    name = models.CharField("І'мя", max_length=100)
    text = models.TextField("Повідомлення", max_length=5000)
    created_at = models.DateTimeField("Дата створення", auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.product}"

    class Meta:
        verbose_name = "Отзив"
        verbose_name_plural = "Отзиви"

product/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField
from .models import Reviews, Rating, RatingStar

class ReviewForm(forms.ModelForm):
    """ Форма отзивів """
    captcha = ReCaptchaField()
    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "text": forms.Textarea(attrs={"class": "form-control", "id": "comment_text"})
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star", )

product/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.http import HttpResponse, JsonResponse

from .models import Product, Category, Image, Rating, Size
from .forms import ReviewForm, RatingForm



class ProductView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'product/home.html', {"products": products})


# 3 спосіб вивести всі категорії
class CategoryGetAll():
    def get_categories(self):
        return Category.objects.all()

class ImagesGetRoot():
    def get_image_root(self):
        return Image.objects.filter('root').value('name')


class ProductListView(CategoryGetAll, ListView):
    model = Product
    queryset = Product.objects.all()
    paginate_by = 3

    # 1 спосіб виввести всі категорії
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        return context



class ProductFilterView(CategoryGetAll, ListView):
    paginate_by = 2
    def get_queryset(self):
        min_price = self.request.GET.getlist("price1")[0]
        max_price = self.request.GET.getlist("price2")[0]
        queryset = Product.objects.filter(category__in=self.request.GET.getlist("category"), price__range=(min_price, max_price)).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["category"] = ''.join([f"category={x}&" for x in self.request.GET.getlist("category")])
        return context


# class JsonProductFilterView(ListView):
#
#     def get_queryset(self):
#         # queryset = Product.objects.filter(
#         #     Q(category__in=self.request.GET.getlist("category")) |
#         #     "price" >= self.request.GET.getlist("price1") &
#         #     "price" <= self.request.GET.getlist("price2")
#         # ).distinct().values("id", "name", "slug", "price")
#         queryset = Product.objects.filter(
#             Q(category__in=self.request.GET.getlist("category"))
#         ).distinct().values("id", "name", "slug", "price")
#         return queryset
#
#     def get(self, request, *args, **kwargs):
#         queryset = list(self.get_queryset())
#         return JsonResponse({"products": queryset}, safe=False)


class ProductDetailView(DetailView):
    model = Product
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        context['form'] = ReviewForm()
        context['sizes'] = Size.objects.all()
        return context


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        product = Product.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.product = product
            form.save()

        return redirect(product.get_absolute_url())


class AddStarRating(View):
    """Добавлення рейтингу фільму"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip


    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                product_id=int(request.POST.get("product")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)



class SearchListView(ListView):
    """Поиск фильмов"""
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(name__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

product/templates/product/product_list.html
{% extends 'base.html' %}

{% load product_tag static i18n %}

{% block header %}
	{% include 'include/header.html ' %}
{% endblock header %}


{% block breadcrumbs %}
	<section class="introBannerHolder d-flex w-100 bgCover" style="background-image: url({% static 'images/b-bg7.jpg' %});">
		<div class="container">
			<div class="row">
				<div class="col-12 pt-lg-23 pt-md-15 pt-sm-10 pt-6 text-center">
					<h1 class="headingIV fwEbold playfair mb-4">Shop</h1>
					<ul class="list-unstyled breadCrumbs d-flex justify-content-center">
						<li class="mr-2"><a href="{% url 'home' %}">Home</a></li>
						<li class="mr-2">/</li>
						<li class="active">Shop</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
{% endblock breadcrumbs %}

{% block content %}
		<!-- twoColumns -->
		<div class="twoColumns container pt-lg-23 pb-lg-20 pt-md-16 pb-md-4 pt-10 pb-4">
			<div class="row">
				<div class="col-12 col-lg-9 order-lg-3">
					<!-- content -->
					<article id="content">
						<!-- show-head -->
						<header class="show-head d-flex flex-wrap justify-content-between mb-7">
							<ul class="list-unstyled viewFilterLinks d-flex flex-nowrap align-items-center">
								<li class="mr-2"><a href="javascript:void(0);" class="active"><i class="fas fa-th-large"></i></a></li>
								<li class="mr-2"><a href="javascript:void(0);"><i class="fas fa-list"></i></a></li>
								<li class="mr-2">Showing 1–9 of 24 results</li>
							</ul>
							<!-- sortGroup -->
							<div class="sortGroup">
								<div class="d-flex flex-nowrap align-items-center">
									<strong class="groupTitle mr-2">Sort by:</strong>
									<div class="dropdown">
										<button class="dropdown-toggle buttonReset" type="button" id="sortGroup" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Default sorting' %}</button>
										<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="sortGroup">
											<li><a href="javascript:void(0);">Default Order</a></li>
											<li><a href="javascript:void(0);">Default Order</a></li>
											<li><a href="javascript:void(0);">Default Order</a></li>
											<li><a href="javascript:void(0);">Default Order</a></li>
										</ul>
									</div>
								</div>
							</div>
						</header>
						<div class="row">
							{% for product in product_list %}
								<!-- featureCol -->
								<div class="col-12 col-sm-6 col-lg-4 featureCol mb-7">
									<div class="border">
										<div class="imgHolder position-relative w-100 overflow-hidden">
											{% for image in product.image_set.all %}
												{% if image.root == True %}
													<img src="{{ image.name.url }}" alt="image description" class="img-fluid w-100">
												{% endif %}
											{% endfor %}
											<ul class="list-unstyled postHoverLinskList d-flex justify-content-center m-0">
												<li class="mr-2 overflow-hidden"><a href="javascript:void(0);" class="icon-heart d-block"></a></li>
												<li class="mr-2 overflow-hidden"><a href="javascript:void(0);" class="icon-cart d-block"></a></li>
												<li class="mr-2 overflow-hidden"><a href="javascript:void(0);" class="icon-eye d-block"></a></li>
												<li class="overflow-hidden"><a href="javascript:void(0);" class="icon-arrow d-block"></a></li>
											</ul>
										</div>
										<div class="text-center py-5 px-4">
											<span class="title d-block mb-2"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></span>
											{% for productaction in product.productaction_set.all %}
												{% if productaction.product.id == product.id %}
													<span class="hotOffer fwEbold text-uppercase text-white position-absolute d-block ml-{% widthratio forloop.counter0 1 8 %}"
														  style="background-color: {{ productaction.action.color }};">{{ productaction.action.name }}</span>
												{% endif %}
											{% endfor %}
											{% if product.get_price_discount == product.price %}
												<span class="price d-block fwEbold">{{ product.price|floatformat:2 }} $</span>
											{% else %}
												<span class="price d-block fwEbold"><del>{{ product.price|floatformat:2 }} $</del>{{ product.get_price_discount|floatformat:2 }} $</span>
											{% endif %}
										</div>
									</div>
								</div>
							{% endfor %}
							<div class="col-12 pt-3 mb-lg-0 mb-md-6 mb-3">
								{% include 'include/pagination.html' %}
							</div>
						</div>
					</article>
				</div>
				<div class="col-12 col-lg-3 order-lg-1">
					<!-- sidebar -->
					<aside id="sidebar">
						<!-- widget -->
						<section class="widget overflow-hidden mb-9">
							<form action="{% url 'search' %}" method="get" class="searchForm position-relative border">
								<fieldset>
									<input type="search" name="q" class="form-control" placeholder="Search product...">
									<button type="submit" class="position-absolute"><i class="icon-search"></i></button>
								</fieldset>
							</form>
						</section>
						<!-- widget -->
						<form action="{% url 'product_filter' %}" method="GET" name="filter" class="filter-ranger-form">
							<section class="widget overflow-hidden mb-9">
								<h3 class="headingVII fwEbold text-uppercase mb-5">{% trans 'PRODUCT CATEGORIES' %}</h3>
								<ul class="list-unstyled categoryList mb-0">
	<!--								{% get_categories as categories %}-->
									{% for category in view.get_categories %}
										<li class="mb-5 overflow-hidden">
											<input name="category" type="checkbox" value="{{ category.id }}">
											<a href="javascript:void(0);">{{ category.name }} <span class="num border float-right">{{ category.get_count_products }}</span></a>
										</li>
									{% endfor %}
								</ul>
							</section>

							<!-- widget -->
							<section class="widget mb-9">
								<h3 class="headingVII fwEbold text-uppercase mb-6">{% trans 'Filter by price' %}</h3>
								<!-- filter ranger form -->
									<div id="slider-range"></div>
									<input type="hidden" id="amount1" name="price1">
									<input type="hidden" id="amount2" name="price2">
									<div class="get-results-wrap d-flex align-items-center justify-content-between">
										<button type="submit" class="btn btnTheme btn-shop fwEbold md-round px-3 pt-1 pb-2 mt-5 text-uppercase">{% trans 'Filter' %}</button>
										<p id="amount" class="mb-0"></p>
									</div>
							</section>

						</form>
						<!-- widget -->
						<section class="widget mb-9">
							<h3 class="headingVII fwEbold text-uppercase mb-6">{% trans 'top rate' %}</h3>
							{% get_top_product count=2 %}
						</section>
						<!-- widget -->
						<section class="widget mb-9">
							<h3 class="headingVII fwEbold text-uppercase mb-5">{% trans 'product tags' %}</h3>
							<ul class="list-unstyled tagNavList d-flex flex-wrap mb-0">
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Plant</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Floor</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Indoor</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Green</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Healthy</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Cactus</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">House plant</a></li>
								<li class="text-center"><a href="javascript:void(0);" class="md-round d-block">Office tree</a></li>
							</ul>
						</section>
					</aside>
				</div>
			</div>
		</div>
>

{% endblock content %}

{% block extra-js %}
	<script src="{% static 'js/scripts.js' %}"></script>
	<script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
{% endblock extra-js %}